name: book_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  in_app_purchase: ^3.1.11
  intl: ^0.19.0
  logger: ^2.0.2+1
  motion_tab_bar: ^2.0.4
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  resize: ^1.0.0
  shared_preferences: ^2.2.2
  skeleton_loader: ^2.0.0+4
  syncfusion_flutter_pdfviewer: ^20.2.7
  url_launcher: ^6.2.4
  flutter_inappwebview: ^5.4.4+3
 

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
